version: '3'
services:
  web:
    build: ../web
    ports:
      - "5000:5000"
    environment:
      - ENV=lab
    depends_on:
      - db

  db:
    build: ../db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
